[base]
background_color = "#161925"
foreground_color = "#c74ded"
opacity = 0.8
# TODO: decide how to configure bar size and scaling, hardcode some value for now
# scale_factor = 1.5

# pre-defined modules can have some additional theming options
[workspaces]
visibility_mode = "monitor_specific"
active_color = "#00c1e4"
inactive_color = "#c74ded"
